#!/usr/bin/env bash
rofi_command="rofi -theme $HOME/.config/rofi/config/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Buttons
layout=$(cat $HOME/.config/rofi/config/powermenu.rasi | grep BUTTON | cut -d'=' -f2 | tr -d '[:blank:],*/')
if [[ "$layout" == "FALSE" ]]; then
  shutdown="⏻"
  reboot="󰑎 "
  lock=""
  suspend=" "
  logout="󰈆"
else
  shutdown="⏻"
  reboot=""
  lock=""
  suspend=" "
  logout="󰈆"
fi
ddir="$HOME/.config/rofi/config"

# Ask for confirmation
rdialog() {
  rofi -dmenu -i -no-fixed-num-lines -p "Are You Sure? : " \
    -theme "$ddir/confirm.rasi"
}

# Display Help
show_msg() {
  rofi -theme "$ddir/askpass.rasi" -e "Options : yes / no / y / n"
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"
chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"

# Exit if no option selected (escape was pressed)
[[ -z "$chosen" ]] && exit 0

case $chosen in
$shutdown)
  ans=$(rdialog) # Removed the &
  if [[ -z "$ans" ]]; then
    exit 0
  elif [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
    systemctl poweroff
  elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
    exit
  else
    show_msg
  fi
  ;;
$reboot)
  ans=$(rdialog) # Removed the &
  if [[ -z "$ans" ]]; then
    exit 0
  elif [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
    systemctl reboot
  elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
    exit
  else
    show_msg
  fi
  ;;
$lock)
  hyprlock
  ;;
$suspend)
  ans=$(rdialog) # Removed the &
  if [[ -z "$ans" ]]; then
    exit 0
  elif [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
    hyprlock && systemctl suspend
  elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
    exit
  else
    show_msg
  fi
  ;;
$logout)
  ans=$(rdialog) # Removed the &
  if [[ -z "$ans" ]]; then
    exit 0
  elif [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
    hyprctl dispatch exit
  elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
    exit
  else
    show_msg
  fi
  ;;
esac
