#!/bin/sh

# Check current DND status using swaync-client
STATUS=$(swaync-client -g | grep '"dnd": true' >/dev/null && echo "true" || echo "false")

toggle() {
  if [ "$STATUS" == "false" ]; then
    swaync-client -d # Enable DND
    eww -c ~/.config/eww/fast-control-menu update dnd-color="rgba(115,75,216,0.7)"
  else
    swaync-client -d # Disable DND
    notify-send --urgency=normal "Не беспокоить" "Функция не беспокоить отключена!"
    eww -c ~/.config/eww/fast-control-menu update dnd-color="rgba(255,255,255,0.15)"
  fi
}

icon() {
  if [ "$STATUS" == "false" ]; then
    echo "" # DND Off (moon/sleep icon)
  else
    echo "󰽥" # DND On (mute/bell-off icon)
  fi
}

status() {
  if [ "$STATUS" == "false" ]; then
    echo "Off"
  else
    echo "On"
  fi
}

if [[ $1 == "--toggle" ]]; then
  toggle
elif [[ $1 == "--icon" ]]; then
  icon
elif [[ $1 == "--status" ]]; then
  status
fi

